- name: 'HITOKANA'
  week: 'Thursday'
  time: '23:00'
  length: 30
- name: 'TOSHITAI'
  week: 'Tuesday'
  time: '23:30'
  length: 30
- name: 'COMEON'
  week: 'Sunday'
  time: '00:00'
  length: 30
- name: 'TRYANGLE_HARMONY'
  week: 'Tuesday'
  time: '21:00'
  length: 30
- name: 'FGO'
  week: 'Friday'
  time: '21:00'
  length: 60
- name: 'AT_LIVING'
  week: 'Monday'
  time: '23:00'
  length: 30
- name: 'SHIROKURO'
  week: 'Sunday'
  time: '01:30'
  length: 30
- name: 'LAUGH_STORY'
  week: 'Wednesday'
  time: '21:00'
  length: 30
